#pragma checksum "C:\Users\SleepDeprivedLoon\source\repos\AverOBus\AverOBus\Platforms\Windows\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "254488CCA3B158FE2DAFC3751A715076CEACD1D2A1CB8A1E13F07247C818C307"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AverOBus.WinUI
{
    partial class App : global::Microsoft.Maui.MauiWinUIApplication
    {
    }
}

